S02 us29 admin product new
WildCodeSchool/orleans-0219-php-lavoliere pull request #142
Opened 2019-06-15 09:05 UTC by vincent-mouline

Install vich_uploader 
Stylize form in new products page
add JS for selected file view

2019-06-15 09:22 UTC, Nawalsubject commented on .gitignore
> +<<<<<<< HEAD
Reste d'un merge ?

2019-06-15 09:27 UTC, Nawalsubject commented on templates/index/index.html.twig
> +                                                                                                        class="a-header">Cueillette
?

2019-06-15 09:31 UTC, Nawalsubject requested changes
Changement du fichier index (home page) pas dans la US, reste d'un merge dans gitignore

2019-06-15 09:59 UTC, vincent-mouline commented on .gitignore
> +<<<<<<< HEAD
Shame, shame

2019-06-15 10:04 UTC, sylvainaubert approved these changes

2019-06-17 08:11 UTC, Nawalsubject approved these changes

2019-06-17 09:56 UTC, BertrandGouny requested changes

2019-06-17 09:56 UTC, BertrandGouny commented on templates/base.html.twig
> +<html lang="fr">
hors US

2019-06-17 09:56 UTC, BertrandGouny commented on templates/product/index.html.twig
> +    <section>
hors US

2019-06-17 09:56 UTC, BertrandGouny commented on templates/index/index.html.twig
> +            <p class="text-center p-title-wrapper"><a href="#" class="a-header">Vente en ligne</a>
Hors US

2019-06-17 09:56 UTC, BertrandGouny commented on src/Entity/Product.php
> +     * @Vich\UploadableField(mapping="product_image", fileNameProperty="picture")
Est ce que la librairie supprime les metadata des photos (exif) ?

2019-06-17 11:53 UTC, vincent-mouline commented on templates/base.html.twig
> +<html lang="fr">
C’était pour résoudre un problème sur le formulaire ( sur l'input fichier au lieu de Browse )

2019-06-17 11:57 UTC, vincent-mouline commented on templates/index/index.html.twig
> +            <p class="text-center p-title-wrapper"><a href="#" class="a-header">Vente en ligne</a>
Ctr + Alt + L suite a un changement de path sur les images produits

2019-06-17 11:58 UTC, vincent-mouline commented on templates/index/index.html.twig
> +            <p class="text-center p-title-wrapper"><a href="#" class="a-header">Vente en ligne</a>
Ctr + Alt + L suite a un changement de path sur les images produits

2019-06-17 12:47 UTC, merged