Us03 us38 page livraison
WildCodeSchool/orleans-0219-php-lavoliere pull request #159
Opened 2019-06-18 10:09 UTC by vincent-mouline

Add OrderController
Add delivery method on OrderController
Stylize delivery.html.twig

2019-06-18 11:30 UTC, Nawalsubject approved these changes

2019-06-18 15:33 UTC, solennelle approved these changes

2019-06-19 07:53 UTC, BertrandGouny requested changes

2019-06-19 07:53 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
donner au personnes identifiées un ROLE_USER par exemple et checker l’identification avec l'annotation IsGranted
si les droits des personnes connecté est amené a évoluer ça serra moins source d'erreur

2019-06-19 08:39 UTC, Nawalsubject approved these changes

2019-06-19 15:45 UTC, merged