S03 us41 edit account
WildCodeSchool/orleans-0219-php-lavoliere pull request #167
Opened 2019-06-18 16:51 UTC by Nawalsubject

Add edit information form page

2019-06-18 18:52 UTC, sylvainaubert requested changes

2019-06-18 18:52 UTC, sylvainaubert commented on assets/scss/my_account.scss
> +    font-family: "Montserrat", sans-serif;
Variable...

2019-06-18 19:21 UTC, sylvainaubert approved these changes

2019-06-19 07:47 UTC, vincent-mouline approved these changes

2019-06-19 07:57 UTC, merged