fonctionnalité "ajouter au panier"
WildCodeSchool/orleans-0219-php-lavoliere pull request #184
Opened 2019-06-19 14:02 UTC by solennelle

2019-06-19 14:27 UTC, Nawalsubject approved these changes

2019-06-19 18:40 UTC, sylvainaubert approved these changes

2019-06-19 19:03 UTC, vincent-mouline approved these changes

2019-06-20 11:39 UTC, BertrandGouny requested changes

2019-06-20 11:39 UTC, BertrandGouny commented on src/Controller/IndexController.php
> +     * @Route("/add-cart-index/{id}", name="add_cart_index", methods={"POST", "GET"})
+1

2019-06-20 11:39 UTC, BertrandGouny commented on src/Service/CartService.php
> +     * @Route("/add/{id}", name="add_cart", methods={"POST", "GET"})
+1

2019-06-20 11:39 UTC, BertrandGouny commented on src/Service/CartService.php
> +            ++$cart[$product->getId()]['quantity'] ;
Créer une entity (non doctrine) pour stocker un produit + une quantité

2019-06-20 13:50 UTC, solennelle commented on src/Service/CartService.php
> +        $product->setQuantity(1);
est-ce que créer un champ (non doctrine) dans l'entité Produit marcherait aussi? Pour avoir juste le produit en lui même dans la session?

2019-06-20 13:51 UTC, solennelle commented on src/Service/CartService.php
> +        $product->setQuantity(1);
@BertrandGouny

2019-06-22 09:44 UTC, sylvainaubert requested changes

2019-06-22 09:44 UTC, sylvainaubert commented on src/Controller/CartController.php
> +        dump($cart);
Un dump oublié

2019-06-24 09:54 UTC, vincent-mouline approved these changes

2019-06-24 13:31 UTC, sylvainaubert approved these changes

2019-06-24 14:03 UTC, merged