S03 us47 admin edit event
WildCodeSchool/orleans-0219-php-lavoliere pull request #195
Opened 2019-06-20 13:17 UTC by Nawalsubject

Stylization of the edit event form

2019-06-20 21:56 UTC, sylvainaubert approved these changes

2019-06-21 06:43 UTC, vincent-mouline approved these changes

2019-06-21 08:13 UTC, BertrandGouny commented
Les fichiers dans public/events/images ne devraient pas être versionnés

2019-06-22 09:32 UTC, vincent-mouline approved these changes

2019-06-22 09:47 UTC, sylvainaubert approved these changes

2019-06-23 19:42 UTC, BertrandGouny requested changes

2019-06-23 19:42 UTC, BertrandGouny commented on templates/account/change_password.html.twig
> +
hors US

2019-06-24 07:24 UTC, vincent-mouline approved these changes

2019-06-24 07:52 UTC, solennelle approved these changes

2019-06-24 07:52 UTC, sylvainaubert approved these changes

2019-06-24 14:05 UTC, merged