S03 us 40 page livraison selection
WildCodeSchool/orleans-0219-php-lavoliere pull request #198
Opened 2019-06-20 20:00 UTC by vincent-mouline

add form in delivery page
stylize form
add __construct in DeliveryType for date interval parameters
add parameters in services.yaml

2019-06-20 21:56 UTC, sylvainaubert approved these changes

2019-06-21 07:07 UTC, solennelle approved these changes

2019-06-21 08:16 UTC, BertrandGouny commented on assets/scss/order.scss
> +    background-color: rgba(0, 0, 0, 0.5);
couleur dans une variable

2019-06-21 08:16 UTC, BertrandGouny commented on assets/scss/order.scss
> +    background-color: transparent;
couleur dans une variable

2019-06-21 08:16 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +            $session->set('delivery', $data['name']);
Utiliser une classe pour stocker les données

2019-06-21 08:16 UTC, BertrandGouny commented on src/Entity/Location.php
>      private $location_type;
location type en boolean ? donner un nom plus parlant

2019-06-22 09:49 UTC, sylvainaubert approved these changes

2019-06-23 19:36 UTC, BertrandGouny requested changes

2019-06-23 19:36 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +//        if (!$session->has('cart')) {
supprimer code commenté

2019-06-23 19:36 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +            $delivery->setLocation($data['name']);
soit utiliser une classe et la lier au formtype,
soit mettre les clés 'name, deliveryDate...' dans des constantes du formtype +rapide ;)

2019-06-24 08:10 UTC, sylvainaubert approved these changes

2019-06-24 08:13 UTC, solennelle approved these changes

2019-06-25 07:31 UTC, merged