change regex for prices assert
WildCodeSchool/orleans-0219-php-lavoliere pull request #205
Opened 2019-06-22 10:13 UTC by vincent-mouline

2019-06-22 10:16 UTC, sylvainaubert approved these changes

2019-06-24 07:07 UTC, solennelle approved these changes

2019-06-24 14:13 UTC, BertrandGouny requested changes

2019-06-24 14:13 UTC, BertrandGouny commented on src/Entity/Product.php
> +     *     "/([0-9]*[.])?[0-9]+/",
si on utilise des , ?

2019-06-24 14:36 UTC, vincent-mouline commented on src/Entity/Product.php
> +     *     "/([0-9]*[.])?[0-9]+/",
le formulaire transforme automatiquement le float avec un '.' si on met une virgule

2019-06-24 19:46 UTC, sylvainaubert approved these changes

2019-06-25 07:32 UTC, BertrandGouny commented on src/Entity/Product.php
> +     *     "/([0-9]*[.])?[0-9]+/",
ok top :)

2019-06-25 07:32 UTC, merged