S03 us36 cart quantity
WildCodeSchool/orleans-0219-php-lavoliere pull request #243
Opened 2019-06-26 09:08 UTC by solennelle

2019-06-26 09:31 UTC, sylvainaubert approved these changes

2019-06-26 09:32 UTC, Nawalsubject approved these changes

2019-06-30 14:19 UTC, vincent-mouline approved these changes

2019-06-30 20:23 UTC, BertrandGouny requested changes

2019-06-30 20:23 UTC, BertrandGouny commented on src/Service/OrderService.php
>      public function calculateTotalByProduct(): void
methodes à revoir avec vincent ou toi ?

2019-07-01 09:09 UTC, Nawalsubject approved these changes

2019-07-01 10:23 UTC, BertrandGouny requested changes

2019-07-01 10:23 UTC, BertrandGouny commented on src/Controller/CartController.php
> +        if (!empty($orderService->getCart())) {
supprimer le if calculateTotalCart doit retourner 0 si pas de cart ainsi que calculateTotalProduct()

2019-07-01 10:23 UTC, BertrandGouny commented on src/Controller/CartController.php
> +        if (!$cart) {
supprimer et getcart doit retourner [] si pas de cart

2019-07-01 11:46 UTC, BertrandGouny commented on src/Service/OrderService.php
> +        if (!$cart) {
supprimer le if, on est sûr d'avoir au moins [] avec getCart

2019-07-01 11:50 UTC, solennelle commented on src/Service/OrderService.php
> +        if (!$cart) {
c'est fait

2019-07-01 14:37 UTC, merged