S03 us53 confirmation order
WildCodeSchool/orleans-0219-php-lavoliere pull request #244
Opened 2019-06-26 09:52 UTC by vincent-mouline

2019-06-26 10:04 UTC, Nawalsubject approved these changes

2019-06-26 10:22 UTC, BertrandGouny requested changes

2019-06-26 10:22 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +        if (empty($session->get('cart'))) {
utiliser orderservice pour accéder au panier en session

2019-06-26 10:22 UTC, BertrandGouny commented on src/Controller/OrderController.php
>          $cart = $session->get('cart');
+1

2019-06-26 10:22 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +        if (empty($session->get('cart'))) {
+1

2019-06-26 10:22 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +        if (empty($session->get('delivery'))) {
utiliser orderservice pour accéder à la livraison en session

2019-06-26 10:22 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +        if (empty($session->get('cart'))) {
+1

2019-06-26 10:22 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +        if (empty($session->get('delivery'))) {
+1

2019-06-26 10:22 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +        session_reset();
on reset pas toute la session juste les clés utilisées par cart et delivery :O

2019-06-26 10:22 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +        $session->clear();
+1

2019-06-26 11:32 UTC, sylvainaubert approved these changes

2019-06-30 19:32 UTC, BertrandGouny requested changes

2019-06-30 19:32 UTC, BertrandGouny commented on src/Controller/OrderController.php
> +                'total' => $orderService->calculateTotalPurchase($purchase)
rappelé ici ?

2019-06-30 19:32 UTC, BertrandGouny commented on src/Service/OrderService.php
> +    public function calculateTotalPurchase(Purchase $purchase) : ?float
getTotal ?

2019-07-01 08:14 UTC, vincent-mouline commented on src/Service/OrderService.php
> +    public function calculateTotalPurchase(Purchase $purchase) : ?float
Corrigé

2019-07-01 08:16 UTC, vincent-mouline commented on src/Controller/OrderController.php
> +                'total' => $orderService->calculateTotalPurchase($purchase)
Je ne comprend pas la question

2019-07-01 09:39 UTC, vincent-mouline commented on src/Controller/OrderController.php
> +                'total' => $orderService->calculateTotalPurchase($purchase)
corrigé

2019-07-01 10:25 UTC, merged